language: perl

perl:
  - "5.16"

services:
  - rabbitmq

before_script:
  - sudo rabbitmqctl add_vhost /test
  - sudo rabbitmqctl add_user npg npg
  - sudo rabbitmqctl set_permissions -p /test npg '.*' '.*' '.*'
